services:
  dinkum-online-app:
    container_name: dinkum-online-app
    build:
      context: .
      target: ${NODE_ENV}
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app/
      - ${SSL_VOLUME}:/cert
