services:
  dinkum-online-app:
    container_name: dinkum-online-app
    build:
      context: .
      target: ${NODE_ENV}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app/
