export const CATCHABLE_TYPE_FISH = 'fish';
export const CATCHABLE_TYPE_BUG = 'bug';
export const CATCHABLE_TYPE_CRITTER = 'critter';

export const CATCHABLE_TYPES = [CATCHABLE_TYPE_FISH, CATCHABLE_TYPE_BUG, CATCHABLE_TYPE_CRITTER];
